# Generated by Django 4.0.5 on 2022-06-10 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='hotel_Main_Img',
            field=models.ImageField(default='logo.png', upload_to='images/'),
        ),
    ]
