# Generated by Django 4.0.5 on 2022-06-10 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0003_project_slug_alter_project_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='hotel_Main_Img',
            new_name='img1',
        ),
        migrations.AddField(
            model_name='project',
            name='img2',
            field=models.ImageField(default='logo.png', upload_to='images/'),
        ),
    ]
