# Generated by Django 4.0.5 on 2022-06-11 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0004_rename_hotel_main_img_project_img1_project_img2'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='intro',
            field=models.TextField(default='This is the intro', max_length=1000),
        ),
    ]
