# Generated by Django 4.0.5 on 2022-06-11 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0005_project_intro'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='tumbnail',
            field=models.ImageField(default='logo.png', upload_to='images/'),
        ),
    ]
