# Generated by Django 4.0.5 on 2022-06-11 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0006_project_tumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='img3',
            field=models.ImageField(default='logo.png', upload_to='images/'),
        ),
    ]
