# Generated by Django 4.0.5 on 2022-06-12 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0007_project_img3'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('desc', models.TextField(max_length=4000)),
                ('author', models.CharField(max_length=50)),
                ('slug', models.CharField(default='', max_length=50)),
                ('release_date', models.DateField()),
                ('tumbnail', models.ImageField(default='logo.png', upload_to='images/')),
            ],
        ),
    ]
